apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oynml6h-a-nodejs 
  janus-idp.io/tekton: oynml6h-a-nodejs
  backstage.io/kubernetes-id: oynml6h-a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oynml6h-a-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  