apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oynml6h-a-nodejs
  janus-idp.io/tekton: oynml6h-a-nodejs
  backstage.io/kubernetes-id: oynml6h-a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oynml6h-a-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
