apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oynml6h-a-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oynml6h-a-nodejs 
  name: oynml6h-a-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oynml6h-a-nodejs 
